version: '3.8'

services:
  database:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: coffee_house
  coffee_house:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    depends_on:
      - database
    ports:
      - "4200:4200"